apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        command:
         - sleep
         - "3600"
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/mnt/mnist"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
